font_family      JetBrains Mono
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        13
enable_audio_bell no
include theme.conf
cursor_trail     1
background_opacity -1
dynamic_background_opacity yes
hide_window_decorations yes

symbol_map U+E000-U+F8FF Symbols Nerd Font Mono
narrow_symbols U+E000-U+F8FF 1

map ctrl+shift+a>m set_background_opacity +0.1
map ctrl+shift+a>l set_background_opacity -0.1
map ctrl+shift+a>d set_background_opacity default
