#!/usr/bin/env bash
# Detect the right Vulkan device for voxtype and pin it. Idempotent.
#
# Why this is a script and not a committed config file:
#   ggml-vulkan always uses `Vulkan0`. On a hybrid-graphics laptop Vulkan0 is the
#   iGPU, so whisper silently runs there -- measured 31.85s vs 2.54s for the same
#   clip on large-v3, with every voxtype status command still reporting healthy.
#   The correct index is per-machine, so committing GGML_VK_VISIBLE_DEVICES=1
#   would reintroduce that 12x regression on any other host. Detect instead.
#
#   Note ggml filters out llvmpipe, so its numbering does NOT match vulkaninfo's.
#   The only trustworthy source is ggml's own enumeration, which is why this
#   invokes voxtype rather than parsing vulkaninfo.
#
# Writes (both untracked, .gitignore'd -- they are host state, not dotfiles):
#   ~/.config/environment.d/90-voxtype-gpu.conf          (login session -> CLI)
#   ~/.config/systemd/user/voxtype.service.d/10-gpu.conf (the daemon)
set -euo pipefail

ok()   { printf '  \033[32m✓\033[0m %s\n' "$*"; }
warn() { printf '  \033[33m!\033[0m %s\n' "$*"; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$*" >&2; exit 1; }

command -v voxtype >/dev/null || { warn "voxtype not installed — skipping GPU pin"; exit 0; }
command -v ffmpeg  >/dev/null || die "ffmpeg required to build the probe clip"

MODEL=$(sed -n 's/^model *= *"\(.*\)"/\1/p' "$HOME/.config/voxtype/config.toml" 2>/dev/null | head -1)
MODEL="${MODEL:-large-v3}"
[ -f "$HOME/.local/share/voxtype/models/ggml-${MODEL}.bin" ] \
  || { warn "model ggml-${MODEL}.bin not downloaded yet — skipping GPU pin"; exit 0; }

TMP=$(mktemp -d); trap 'rm -rf "$TMP"' EXIT
ffmpeg -y -loglevel error -f lavfi -i anullsrc=r=16000:cl=mono -t 0.3 \
       -c:a pcm_s16le "$TMP/p.wav"

# VAD short-circuits on silence before whisper initialises, so a silent probe
# under the normal config prints no ggml_vulkan lines at all. Disable VAD here,
# and point at a model that actually exists (the shipped default is base.en).
{ sed "s|^model = .*|model = \"$MODEL\"|" /etc/voxtype/config.toml
  printf '\n[vad]\nenabled = false\n'; } > "$TMP/probe.toml"

# `env -u`, not `VAR=`: an empty GGML_VK_VISIBLE_DEVICES hides EVERY device, and
# unsetting also undoes a previous pin so re-runs re-detect honestly.
#
# This probe loads the full model (~5s) because ggml only enumerates when whisper
# initialises -- a VAD-only run prints nothing. Running it beside a live daemon is
# safe in both directions: unpinned it lands on Vulkan0, and where that's an iGPU
# (uma: 1) it draws on system RAM and never touches the daemon's VRAM. Where
# Vulkan0 IS the dGPU it may abort on the second allocation -- but ggml prints the
# device list well before allocating, so `|| true` keeps the enumeration either way.
ENUM=$(env -u GGML_VK_VISIBLE_DEVICES voxtype -c "$TMP/probe.toml" \
        transcribe "$TMP/p.wav" 2>&1 | grep -oE 'ggml_vulkan: [0-9]+ = .*' || true)
[ -n "$ENUM" ] || die "could not enumerate Vulkan devices"
echo "$ENUM" | sed 's/^/     /'

IDX=$(echo "$ENUM" | awk -F'[:=]' '
  { idx=$2+0; line=$0; score=0
    if (line ~ /llvmpipe/)               score-=100
    if (line ~ /matrix cores: (KHR|NV)/) score+=10
    if (line ~ /uma: 0/)                 score+=5
    if (score>best || best=="") { best=score; pick=idx }
  } END { print pick }')
NAME=$(echo "$ENUM" | grep -E "^ggml_vulkan: $IDX = " | sed 's/.*= //; s/ (.*//')

mkdir -p "$HOME/.config/environment.d" "$HOME/.config/systemd/user/voxtype.service.d"
cat > "$HOME/.config/environment.d/90-voxtype-gpu.conf" <<EOF
# Generated by dotfiles/scripts/voxtype-gpu-pin.sh -- do not commit, host-specific.
# ggml device $IDX = $NAME
GGML_VK_VISIBLE_DEVICES=$IDX
EOF
cat > "$HOME/.config/systemd/user/voxtype.service.d/10-gpu.conf" <<EOF
[Service]
Environment=GGML_VK_VISIBLE_DEVICES=$IDX
EOF
ok "pinned ggml device $IDX: $NAME"

echo "$ENUM" | grep -qE "^ggml_vulkan: $IDX .*matrix cores: none" \
  && warn "chosen device has no matrix cores — no dGPU here? expect slow transcription"

# large-v3 needs ~3.1GB resident. Warn rather than switch: the model is a
# committed preference, and silently downgrading it would hide the problem.
if command -v nvidia-smi >/dev/null && [ "$MODEL" = "large-v3" ]; then
  TOTAL=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader,nounits | head -1)
  [ "${TOTAL:-0}" -lt 3600 ] 2>/dev/null \
    && warn "only ${TOTAL}MiB VRAM; large-v3 needs ~3100MiB. Consider large-v3-turbo."
fi

systemctl --user daemon-reload 2>/dev/null || true
systemctl --user is-active voxtype >/dev/null 2>&1 && systemctl --user restart voxtype && \
  ok "voxtype restarted onto device $IDX" || true
